title: KI und Kopfarbeit
description: Was kann ChatGPT & Co? Welche Denkwerkzeuge gibt es? Und wie verbinde ich das?
theme: just-the-docs

url: https://tenorix.github.io/ki-und-kopfarbeit

enable_copy_code_button: true

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

