site_name: ki-und-kopfarbeit
theme:
  name: material
  features:
    - toc.integrate
    - content.code.copy
    

nav:
  - Home: index.md
  - ChatGPT effizient nutzen - mehr als nur einzelne Prompts: chatbots-richtig-nutzen.md
  - Lernen mit dem Chatbot: lernen-mit-dem-chatbot.md
  - Wie funktioniert ein Chatbot: wie-funktioniert-ein-chatbot-llm.md
  - Impressum: impressum.md
  - Datenschutzerklärung: datenschutz.md
