name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Change if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
          env:
            GH_TOKEN: ${{ secrets.GH_PAT }}
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/tenorix/ki-und-kopfarbeit.git
            mkdocs gh-deploy --force
